config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
    get '/signup' => 'users#new'
    post '/users' => 'users#create'
    get '/signin' => 'sessions#new'
    post '/signin' => 'sessions#create'
    get '/signout' => 'sessions#destroy'
    resources :products do
      resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  accepts_nested_attributes_for :reviews
  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true
  before_save(:titleize_product)


  scope :most_reviews, -> {(
    select("products.id, products.name, products.cost, products.country_of_origin, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
    )}

  scope :most_recent, -> { order(created_at: :desc).limit(3)}

  scope :country_of_origin, -> (country_of_origin_parameter) { where(country_of_origin: "USA") }

  private
  def titleize_product
    self.name = self.name.titleize
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :content_body, presence: true
  validates :rating, presence: true
  validates :content_body, length: { in: 50..250 }
  validates :rating, numericality: { only_integer: true,  less_than_or_equal_to_5: true }
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user 
      flash[:alert] = "You must log in to visit that page."
      redirect_to '/'
    end
  end

  def admin
    if !current_user
      flash[:alert] = "You must log in to visit that page."
      redirect_to '/'
    elsif !current_user.admin
      flash[:alert] = "You need to be an admin to perform that action!"
      redirect_to '/'
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :admin, only: [:create, :update, :delete]

  def index
    @products = Product.all
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully created!"
      redirect_to products_path
    else
      flash[:notice] = "Product was not created!"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    if params[:most_recent]
      @products = @products.most_recent(params[:most_recent])
    else
      @product = Product.find(params[:id])
    end
    render :show
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
    flash[:alert] = "Product successfully updated!"
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
          flash[:notice] = "You've deleted this product!"
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :cost, :country_of_origin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize, only: [:create]

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully created!"
      redirect_to product_path(@product)
    else
      flash[:alert] = "Review was not created!"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end

  private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating, :product_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing up."
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :admin, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3><span>Please fix these errors:</span></h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><span><%= message %></span></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>
<div class="form">
  <%= form_for @product do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <br>
    <br>
    <%= f.label :cost %>
    <%= f.text_field :cost %>
    <br>
    <br>
    <br>
    <%= f.label :country_of_origin %>
    <%= f.text_field :country_of_origin %>
    <p><%= f.submit  %></p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoreDatabase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%= current_user.email %> | <%= link_to "Sign out", '/signout' %>
    <% else %>
      <%= link_to "Sign up", 'signup' %> | <%= link_to "Sign in", '/signin' %>
    <% end %>

    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1><span>Edit product</span></h1>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<div class="title">
  <h1><span>Mario's Specialty Appliances</span></h1>
</div>

<div class="product_listing">
<h1><span>Products</span></h1>
<p><span><%= link_to "Create new product", new_product_path %></span></p>
<% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p><span>There are no products yet.</span></p>
<% end %>
</div>

app/views/products/new.html.erb
<h1><span>New product</span></h1>

<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<h1><span><%= @product.name %></span></h1>
<h3><span><%= @product.cost %></span></h3>
<h3><span><%= @product.country_of_origin %></span></h3>

<% if @product.reviews.any? %>
  <h4><span>Here are the reviews for this product:</span></h4>

  <% @product.reviews.each do |review| %>
    <ul>
      <li><span>
        <%= link_to review.author, product_review_path(@product, review) %>
      </span></li>
    </ul>
  <% end %>
<% else %>
  <p><span>No reviews are listed for this product.</span></p>
<% end %>

<p><span><%= link_to "Add a review", new_product_review_path(@product) %></span></p>

<p><span><%= link_to "Edit", edit_product_path(@product) %><span></p>
<p><span><%= link_to "Delete product", product_path(@product),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></span></p>

  <p><span><%= link_to "Return to products", products_path %></span></p>

app/views/reviews/edit.html.erb
<h1><span>Edit review:</span></h1>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.label :rating %>
  <%= f.text_area :rating %>
  <p><span><%= f.submit %></span></p>
<% end %>

app/views/reviews/new.html.erb
<h1><span>Add a new review:</span></h1>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.label :rating %>
  <%= f.text_area :rating %>
  <p><span><%= f.submit %></span></p>
<% end %>

app/views/reviews/show.html.erb
<h1><span>Product: <%= @product.name %></span></h1>
<h2><span>Review by: <%= @review.author %></span></h2>
<h3><span>Rating: <%= @review.rating %> / 5</span></h3>
<h3><span><%= @review.content_body %></span></h3>

<p><span><%= link_to "Edit review", edit_product_review_path(@product, @review) %></span></p>
<p><span><%= link_to "Delete review", product_review_path(@product, @review),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></span></p>

<p><span><%= link_to "Return to product", product_path(@product) %></span></p>

app/views/users/new.html.erb
<h1><span> Sign up</span></h1>
<%= form_for @user do |f| %>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <%= f.label "Admin" %>
  <%= f.check_box :admin, {}, "true", "false" %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>